apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
  labels:
    app: {{ .Values.microservice.name }}
spec:
  replicas: {{ .Values.microservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.microservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.microservice.name }}
    spec:
      containers:
        - name: {{ .Values.microservice.name }}
          image: {{ .Values.workload.image }}:{{ .Values.workload.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.workload.port }}
          resources:
            limits:
              memory: {{ .Values.workload.resources.memory }}
              cpu: {{ .Values.workload.resources.cpu }}
            requests:
              memory: {{ .Values.workload.resources.memory }}
              cpu: {{ .Values.workload.resources.cpu }}