apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app # Tên đồng nhất với Service
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          # Chỗ này để 'latest' hoặc 'placeholder' 
          # Kustomize sẽ tự động ghi đè mã SHA vào đây khi GHA chạy
          image: congthanh19/demo-app:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "200m"