apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Khai báo tất cả các file manifest bạn muốn triển khai
resources:
- deployment.yaml
- service.yaml
images:
  - name: congthanh19/demo-app
    newTag: latest

