microservice:
  name: flask-app
  namespace: my-flask-app
  replicas: 2
  minReplicas: 1
  maxReplicas: 5
workload:
  image: congthanh19/flask-app
  tag: "f34b1a5806a38248b6aeac288d0573547a589776"
  port: 5000
  resources:
    memory: "256Mi"
    cpu: "128m"
