microservice:
  name: flask-app
  namespace: my-flask-app
  replicas: 2
  minReplicas: 1
  maxReplicas: 5
workload:
  image: congthanh19/flask-app
  tag: "22d3978e3f97d740cf7f126abd4c4b86649aca31"
  port: 5000
  resources:
    memory: "256Mi"
    cpu: "128m"
