microservice:
  name: flask-app
  namespace: my-flask-app
  replicas: 2
  minReplicas: 1
  maxReplicas: 5
workload:
  image: congthanh19/flask-app
  tag: "b1850ca3e546c7cd9ffff9c6f3b130a3331f1e07"
  port: 5000
  resources:
    memory: "256Mi"
    cpu: "128m"
